import type {
  SentenceSlot,
  VocabularyWord,
  WordCategory,
  WordId,
  WordInventory,
} from "./types";

export const WORD_CATEGORY_LABELS: Readonly<Record<WordCategory, string>> = {
  subject: "主体・対象",
  condition: "条件",
  connector: "接続",
  action: "行動",
  modifier: "修飾",
};

const SUBJECT_FLOW = {
  connectsFrom: ["connector", "action"] as const,
  connectsTo: ["condition", "modifier"] as const,
};

function vocabularyWord(
  word: Omit<VocabularyWord, "duplicateRule"> & {
    duplicateRule?: VocabularyWord["duplicateRule"];
  },
): VocabularyWord {
  return {
    ...word,
    duplicateRule: word.duplicateRule ?? {
      kind: "upgrade",
      maxRank: 3,
      powerPerRank: 0,
    },
  };
}

export const VOCABULARY: readonly VocabularyWord[] = [
  vocabularyWord({
    id: "subject.self",
    label: "自分",
    category: "subject",
    grammarRole: "条件の主体／行動の対象",
    effect: { kind: "subject", subject: "self" },
    allowedSlots: ["subject", "target"],
    ...SUBJECT_FLOW,
    rarity: "basic",
    rewardWeight: 1,
    tooltip: "プレイヤー自身を指す。守る、回復するの対象に使える。",
    example: "自分が傷ついているなら、自分を回復する。",
    unlockAfterBattle: 0,
  }),
  vocabularyWord({
    id: "subject.enemy",
    label: "敵",
    category: "subject",
    grammarRole: "条件の主体／行動の対象",
    effect: { kind: "subject", subject: "enemy" },
    allowedSlots: ["subject", "target"],
    ...SUBJECT_FLOW,
    rarity: "basic",
    rewardWeight: 1,
    tooltip: "現在の敵を指す。攻撃や状態操作の対象に使う。",
    example: "敵が近いなら、敵を攻撃する。",
    unlockAfterBattle: 0,
  }),
  vocabularyWord({
    id: "subject.weakest",
    label: "最も弱い対象",
    category: "subject",
    grammarRole: "優先対象",
    effect: { kind: "subject", subject: "weakest" },
    allowedSlots: ["target"],
    ...SUBJECT_FLOW,
    rarity: "rare",
    rewardWeight: 0.55,
    tooltip: "HPの割合が低い側を対象にする。",
    example: "最も弱い対象を回復する。",
    unlockAfterBattle: 1,
  }),
  vocabularyWord({
    id: "subject.last_actor",
    label: "直前に動いた対象",
    category: "subject",
    grammarRole: "履歴対象",
    effect: { kind: "subject", subject: "last_actor" },
    allowedSlots: ["target"],
    ...SUBJECT_FLOW,
    rarity: "rare",
    rewardWeight: 0.45,
    tooltip: "直前の因果ログで行動した側を対象にする。",
    example: "直前に動いた対象を止める。",
    unlockAfterBattle: 2,
  }),
  vocabularyWord({
    id: "condition.always",
    label: "いつでも",
    category: "condition",
    grammarRole: "無条件",
    effect: { kind: "condition", condition: "always" },
    allowedSlots: ["condition"],
    connectsFrom: ["subject"],
    connectsTo: ["connector"],
    rarity: "basic",
    rewardWeight: 0.5,
    tooltip: "状態を問わず行動する。短いが、敵の反応を受けやすい。",
    example: "自分がいつでもなら、敵を攻撃する。",
    unlockAfterBattle: 0,
  }),
  vocabularyWord({
    id: "condition.enemy_near",
    label: "近くにいる",
    category: "condition",
    grammarRole: "距離条件",
    effect: { kind: "condition", condition: "enemy_near" },
    allowedSlots: ["condition"],
    connectsFrom: ["subject"],
    connectsTo: ["connector"],
    rarity: "basic",
    rewardWeight: 0.7,
    tooltip: "敵との戦闘中に成立する基本条件。",
    example: "敵が近くにいるなら、敵を攻撃する。",
    unlockAfterBattle: 0,
  }),
  vocabularyWord({
    id: "condition.player_hurt",
    label: "傷ついている",
    category: "condition",
    grammarRole: "HP条件",
    effect: { kind: "condition", condition: "player_hurt" },
    allowedSlots: ["condition"],
    connectsFrom: ["subject"],
    connectsTo: ["connector"],
    rarity: "basic",
    rewardWeight: 0.8,
    tooltip: "プレイヤーのHPが最大値未満なら成立する。",
    example: "自分が傷ついているなら、自分を回復する。",
    unlockAfterBattle: 0,
  }),
  vocabularyWord({
    id: "condition.player_attacked",
    label: "攻撃された",
    category: "condition",
    grammarRole: "被弾条件",
    effect: { kind: "condition", condition: "player_attacked" },
    allowedSlots: ["condition"],
    connectsFrom: ["subject"],
    connectsTo: ["connector"],
    rarity: "common",
    rewardWeight: 1.1,
    tooltip: "前の手番で敵から攻撃を受けていると成立する。",
    example: "自分が攻撃されたなら、敵へ反撃する。",
    unlockAfterBattle: 0,
  }),
  vocabularyWord({
    id: "condition.enemy_enraged",
    label: "怒っている",
    category: "condition",
    grammarRole: "敵状態条件",
    effect: { kind: "condition", condition: "enemy_enraged" },
    allowedSlots: ["condition"],
    connectsFrom: ["subject"],
    connectsTo: ["connector"],
    rarity: "common",
    rewardWeight: 1.2,
    tooltip: "敵に怒り状態が付いたとき成立する。",
    example: "敵が怒っているなら、自分を守る。",
    unlockAfterBattle: 0,
  }),
  vocabularyWord({
    id: "condition.enemy_watching",
    label: "こちらを見ている",
    category: "condition",
    grammarRole: "視線条件",
    effect: { kind: "condition", condition: "enemy_watching" },
    allowedSlots: ["condition"],
    connectsFrom: ["subject"],
    connectsTo: ["connector"],
    rarity: "common",
    rewardWeight: 1.15,
    tooltip: "敵に視線状態があると成立する。",
    example: "敵がこちらを見ているなら、敵に光を当てる。",
    unlockAfterBattle: 1,
  }),
  vocabularyWord({
    id: "condition.enemy_not_watching",
    label: "見ていない",
    category: "condition",
    grammarRole: "反転視線条件",
    effect: { kind: "condition", condition: "enemy_not_watching" },
    allowedSlots: ["condition"],
    connectsFrom: ["subject"],
    connectsTo: ["connector"],
    rarity: "rare",
    rewardWeight: 0.9,
    tooltip: "敵が視線を失っていると成立する。",
    example: "敵が見ていないなら、敵を拘束する。",
    unlockAfterBattle: 1,
  }),
  vocabularyWord({
    id: "condition.enemy_stopped",
    label: "止まっている",
    category: "condition",
    grammarRole: "停止条件",
    effect: { kind: "condition", condition: "enemy_stopped" },
    allowedSlots: ["condition"],
    connectsFrom: ["subject"],
    connectsTo: ["connector"],
    rarity: "common",
    rewardWeight: 1.15,
    tooltip: "前の文章で敵を停止させたとき成立する。",
    example: "敵が止まっているなら、敵を拘束する。",
    unlockAfterBattle: 1,
  }),
  vocabularyWord({
    id: "condition.enemy_bound",
    label: "拘束されている",
    category: "condition",
    grammarRole: "拘束条件",
    effect: { kind: "condition", condition: "enemy_bound" },
    allowedSlots: ["condition"],
    connectsFrom: ["subject"],
    connectsTo: ["connector"],
    rarity: "rare",
    rewardWeight: 0.9,
    tooltip: "敵が拘束状態なら成立する。攻撃が強くなる。",
    example: "敵が拘束されているなら、敵を攻撃する。",
    unlockAfterBattle: 2,
  }),
  vocabularyWord({
    id: "condition.enemy_named",
    label: "名前を呼ばれた",
    category: "condition",
    grammarRole: "名前条件",
    effect: { kind: "condition", condition: "enemy_named" },
    allowedSlots: ["condition"],
    connectsFrom: ["subject"],
    connectsTo: ["connector"],
    rarity: "rare",
    rewardWeight: 1.1,
    tooltip: "前の文章で敵の名前を呼んでいると成立する。",
    example: "敵が名前を呼ばれたなら、敵を止める。",
    unlockAfterBattle: 2,
  }),
  vocabularyWord({
    id: "connector.then",
    label: "なら",
    category: "connector",
    grammarRole: "条件接続",
    effect: { kind: "connector", connector: "then" },
    allowedSlots: ["connector"],
    connectsFrom: ["condition"],
    connectsTo: ["action"],
    rarity: "basic",
    rewardWeight: 0.5,
    tooltip: "条件が成立したとき、後ろの行動を実行する。",
    example: "敵が近い、なら、攻撃する。",
    unlockAfterBattle: 0,
  }),
  vocabularyWord({
    id: "connector.after",
    label: "その後",
    category: "connector",
    grammarRole: "順序接続",
    effect: { kind: "connector", connector: "after" },
    allowedSlots: ["connector"],
    connectsFrom: ["condition"],
    connectsTo: ["action"],
    rarity: "common",
    rewardWeight: 1.05,
    tooltip: "直前の文章が実行済みで、条件も成立したとき使える。",
    example: "敵が止まっている、その後、拘束する。",
    unlockAfterBattle: 0,
  }),
  vocabularyWord({
    id: "connector.whenever",
    label: "たびに",
    category: "connector",
    grammarRole: "反復接続",
    effect: { kind: "connector", connector: "whenever" },
    allowedSlots: ["connector"],
    connectsFrom: ["condition"],
    connectsTo: ["action"],
    rarity: "rare",
    rewardWeight: 0.8,
    tooltip: "条件が成立すると、行動を二回試す。",
    example: "自分が攻撃された、たびに、反撃する。",
    unlockAfterBattle: 1,
  }),
  vocabularyWord({
    id: "action.attack",
    label: "攻撃する",
    category: "action",
    grammarRole: "攻撃行動",
    effect: {
      kind: "action",
      action: "attack",
      basePower: 4,
      allowedTargets: ["enemy", "weakest", "last_actor"],
    },
    allowedSlots: ["action"],
    connectsFrom: ["connector"],
    connectsTo: ["subject", "modifier"],
    rarity: "basic",
    rewardWeight: 0.8,
    tooltip: "敵へ基礎4ダメージ。拘束中なら追加ダメージ。",
    example: "敵が近くにいるなら、敵を攻撃する。",
    unlockAfterBattle: 0,
    duplicateRule: { kind: "upgrade", maxRank: 3, powerPerRank: 1 },
  }),
  vocabularyWord({
    id: "action.guard",
    label: "守る",
    category: "action",
    grammarRole: "防御行動",
    effect: {
      kind: "action",
      action: "guard",
      basePower: 3,
      allowedTargets: ["self", "weakest"],
    },
    allowedSlots: ["action"],
    connectsFrom: ["connector"],
    connectsTo: ["subject", "modifier"],
    rarity: "basic",
    rewardWeight: 0.9,
    tooltip: "この手番の被害を3減らす。重複取得で防御量が増える。",
    example: "自分が傷ついているなら、自分を守る。",
    unlockAfterBattle: 0,
    duplicateRule: { kind: "upgrade", maxRank: 3, powerPerRank: 1 },
  }),
  vocabularyWord({
    id: "action.heal",
    label: "回復する",
    category: "action",
    grammarRole: "回復行動",
    effect: {
      kind: "action",
      action: "heal",
      basePower: 3,
      allowedTargets: ["self", "weakest"],
    },
    allowedSlots: ["action"],
    connectsFrom: ["connector"],
    connectsTo: ["subject", "modifier"],
    rarity: "basic",
    rewardWeight: 0.85,
    tooltip: "HPを3回復する。最大HPは超えない。",
    example: "自分が傷ついているなら、自分を回復する。",
    unlockAfterBattle: 0,
    duplicateRule: { kind: "upgrade", maxRank: 3, powerPerRank: 1 },
  }),
  vocabularyWord({
    id: "action.stop",
    label: "止める",
    category: "action",
    grammarRole: "停止行動",
    effect: {
      kind: "action",
      action: "stop",
      basePower: 0,
      allowedTargets: ["enemy", "last_actor"],
    },
    allowedSlots: ["action"],
    connectsFrom: ["connector"],
    connectsTo: ["subject", "modifier"],
    rarity: "common",
    rewardWeight: 1.05,
    tooltip: "敵を一手止める。名前や光と組み合わせると確実。",
    example: "敵が名前を呼ばれたなら、敵を止める。",
    unlockAfterBattle: 0,
  }),
  vocabularyWord({
    id: "action.bind",
    label: "拘束する",
    category: "action",
    grammarRole: "拘束行動",
    effect: {
      kind: "action",
      action: "bind",
      basePower: 0,
      allowedTargets: ["enemy", "last_actor"],
      requiresEnemyStatus: "stopped",
    },
    allowedSlots: ["action"],
    connectsFrom: ["connector"],
    connectsTo: ["subject", "modifier"],
    rarity: "rare",
    rewardWeight: 0.9,
    tooltip: "停止中の敵を拘束する。拘束中は攻撃が強くなる。",
    example: "敵が止まっているなら、敵を拘束する。",
    unlockAfterBattle: 1,
  }),
  vocabularyWord({
    id: "action.call_name",
    label: "名前を呼ぶ",
    category: "action",
    grammarRole: "名前行動",
    effect: {
      kind: "action",
      action: "call_name",
      basePower: 0,
      allowedTargets: ["enemy"],
    },
    allowedSlots: ["action"],
    connectsFrom: ["connector"],
    connectsTo: ["subject", "modifier"],
    rarity: "rare",
    rewardWeight: 1.2,
    tooltip: "敵を名前を呼ばれた状態にする。忘名王への決め手。",
    example: "敵が近くにいるなら、敵の名前を呼ぶ。",
    unlockAfterBattle: 1,
  }),
  vocabularyWord({
    id: "action.shine",
    label: "光を当てる",
    category: "action",
    grammarRole: "光行動",
    effect: {
      kind: "action",
      action: "shine",
      basePower: 0,
      allowedTargets: ["enemy"],
    },
    allowedSlots: ["action"],
    connectsFrom: ["connector"],
    connectsTo: ["subject", "modifier"],
    rarity: "common",
    rewardWeight: 1.15,
    tooltip: "敵へ光を当てる。視線を使う敵を停止させる。",
    example: "敵がこちらを見ているなら、敵に光を当てる。",
    unlockAfterBattle: 0,
  }),
  vocabularyWord({
    id: "action.counter",
    label: "反撃する",
    category: "action",
    grammarRole: "反撃行動",
    effect: {
      kind: "action",
      action: "counter",
      basePower: 6,
      allowedTargets: ["enemy", "last_actor"],
    },
    allowedSlots: ["action"],
    connectsFrom: ["connector"],
    connectsTo: ["subject", "modifier"],
    rarity: "rare",
    rewardWeight: 0.9,
    tooltip: "攻撃された条件と組み合わせると強い6ダメージ。",
    example: "自分が攻撃されたなら、敵へ反撃する。",
    unlockAfterBattle: 0,
    duplicateRule: { kind: "upgrade", maxRank: 3, powerPerRank: 1 },
  }),
  vocabularyWord({
    id: "modifier.once",
    label: "一度だけ",
    category: "modifier",
    grammarRole: "回数修飾",
    effect: { kind: "modifier", modifier: "once" },
    allowedSlots: ["modifier"],
    connectsFrom: ["action"],
    connectsTo: [],
    rarity: "basic",
    rewardWeight: 0.45,
    tooltip: "行動を一度だけ実行する。敵の反応を増やさない。",
    example: "敵を一度だけ攻撃する。",
    unlockAfterBattle: 0,
  }),
  vocabularyWord({
    id: "modifier.twice",
    label: "二回",
    category: "modifier",
    grammarRole: "回数修飾",
    effect: { kind: "modifier", modifier: "twice" },
    allowedSlots: ["modifier"],
    connectsFrom: ["action"],
    connectsTo: [],
    rarity: "common",
    rewardWeight: 0.95,
    tooltip: "同じ行動を二回行う。反応型の敵には危険な場合がある。",
    example: "敵を二回攻撃する。",
    unlockAfterBattle: 0,
  }),
  vocabularyWord({
    id: "modifier.again",
    label: "もう一度",
    category: "modifier",
    grammarRole: "再実行修飾",
    effect: { kind: "modifier", modifier: "again" },
    allowedSlots: ["modifier"],
    connectsFrom: ["action"],
    connectsTo: [],
    rarity: "rare",
    rewardWeight: 0.8,
    tooltip: "直前の文章と同じ行動なら、もう一度実行する。",
    example: "直前の攻撃をもう一度行う。",
    unlockAfterBattle: 1,
  }),
  vocabularyWord({
    id: "modifier.negate",
    label: "ではない",
    category: "modifier",
    grammarRole: "条件反転",
    effect: { kind: "modifier", modifier: "negate" },
    allowedSlots: ["modifier"],
    connectsFrom: ["action"],
    connectsTo: [],
    rarity: "rare",
    rewardWeight: 0.65,
    tooltip: "条件の成立／不成立を反転して行動する。",
    example: "敵が見ている、ではないなら、拘束する。",
    unlockAfterBattle: 1,
  }),
] as const;

export const VOCABULARY_BY_ID: Readonly<Record<WordId, VocabularyWord>> =
  Object.fromEntries(VOCABULARY.map((word) => [word.id, word]));

export const STARTER_WORD_IDS = [
  "subject.self",
  "subject.enemy",
  "condition.always",
  "condition.enemy_near",
  "condition.player_hurt",
  "connector.then",
  "action.attack",
  "action.guard",
  "action.heal",
  "modifier.once",
] as const;

export const SENTENCE_SLOT_LABELS: Readonly<Record<SentenceSlot, string>> = {
  subject: "誰が",
  condition: "どんな時",
  connector: "つなぎ",
  action: "何をする",
  target: "誰に",
  modifier: "どうする",
};

export function createStarterInventory(): WordInventory {
  return Object.fromEntries(
    STARTER_WORD_IDS.map((id) => [id, { count: 1, rank: 1 }]),
  );
}

export function getOwnedWords(
  inventory: WordInventory,
  category?: WordCategory,
): readonly VocabularyWord[] {
  return VOCABULARY.filter(
    (word) => inventory[word.id] && (!category || word.category === category),
  );
}

export function wordFitsSlot(word: VocabularyWord, slot: SentenceSlot): boolean {
  return word.allowedSlots.includes(slot);
}
